trigger:
- main
- development
- feat-*

pr:
- main
- development

pool:
  vmImage: 'ubuntu-latest'

stages:
# Build Stage: Runs for all branches
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Angular App'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '>=16.0.0'
        displayName: 'Install Node.js'

      - script: |
          npm install -g @angular/cli
          npm install
        displayName: 'Install Dependencies'

      - script: npm run build -- --configuration production
        displayName: 'Build Angular App'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'dist/creditsplit'
          ArtifactName: 'creditsplit-build'
        displayName: 'Publish Build Artifacts'

# Deploy Stage: Runs only for main and development branches
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/development')))
  jobs:
  - job: Deploy
    displayName: 'Deploy to Azure Static Web App'
    steps:
      - task: AzureStaticWebApp@0
        inputs:
          azure_static_web_apps_api_token: $(STATIC_WEB_APP_API_TOKEN)
          app_location: 'dist/creditsplit'
          output_location: '/'
        displayName: 'Deploy Angular App'
